### ISSUE TITLE
🔴 BUG: % is not working properly

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#19]
Hey there, 
Hi @jiri132,
I'm having trouble with the percentage function since I added the decimal feature. Would you mind taking a look and fixing it? 

Thank you kindly!
Best regards
NH

**Comment by arenodi** [comment]
Hey I would like to tackle this issue.

**Comment by N3v1** [comment]
> Hey I would like to tackle this issue. Do you have more information?

Sure @arenodi,
before I merged the PR (#18) the percent functionality worked fine but after it, it doesn't work properly. 
Example: 100 - 50% = **50**
<img width="1552" alt="Bildschirmfoto 2023-08-13 um 12 04 29" src="https://github.com/N3v1/Calculator/assets/129311622/efdd6b9a-5d1b-4c0b-acd2-801d3b54782c">

The calculator says 99.5 but it should be 50. 
Before I merged #18 this example worked fine and it printed 50

**Comment by arenodi** [comment]
hey @N3v1 , there are a few things to take into consideration:

### Lines [73 to 77](https://github.com/N3v1/Calculator/blob/22ad8e414d1c4b1e189f3485cc77a4b7ffa371d4/index.js#L73C6-L77C8):
* The `if` content will never run, because the `typeof` of the arg `number` will always be a `string`.
* In `else` body, the `percentageToDecimal()` function is called and then...

### Lines [48 to 50](https://github.com/N3v1/Calculator/blob/22ad8e414d1c4b1e189f3485cc77a4b7ffa371d4/index.js#L47C1-L50C2):
* The `percentageToDecimal()` function receives the `string` and the parses it with `new Decimal()`.
* `new Decimal()` returns a decimal and then the decimal is divided by  100.
* `percentageToDecimal()` then returns the quotient of that operation.

That is, the '50' as a string will trigger the `percentageToDecimal()` function that will invoke the `new Decimal()` and be divided by 100, and then returned as `0.5`, hence `100 - 0.5 = 99.5`.

### Fix:
To fix this problem I made a few changes on the code:
1. Add 'math.js' library to parse and evaluate expressions.
    * Lines [28-34](https://github.com/arenodi/Calculator/blob/cb79e3e8e2ba5c4709e886b74d27bb19ee64e99a/index.html#L28C5-L34C15)
1. Remove library 'decimal.js'.
1. Remove `percentageToDecimal()` function.
1. Partially refactoring.
    * Lines [43-49](https://github.com/arenodi/Calculator/blob/cb79e3e8e2ba5c4709e886b74d27bb19ee64e99a/index.js#L43C1-L59C2)

**Note:** With 'math.js' library the expression is compiled from the way it is typed and then evaluated, eliminating the need to custom parsing it. Also the lib is powerful enough to support future features as advanced arithmetics operations.

I will create a pull request on it.

**Comment by N3v1** [comment]
Thank you @arenodi for your work
